env:
  NODE_ENV: staging

envSecrets:
  MONGODB_URI: openfinance-chatbot
  DATABASE_NAME: openfinance-chatbot
  APP_NAME: openfinance-chatbot
  AWS_REGION: openfinance-chatbot
  CHAT_COMPLETIONS_MODEL_ID: openfinance-chatbot
  CHECKPOINTS_AIO_COLLECTION: openfinance-chatbot
  CHECKPOINTS_WRITES_AIO_COLLECTION: openfinance-chatbot
  OPEN_FINANCE_API_URL: openfinance-chatbot
  NODE_ENV: openfinance-chatbot

serviceAccount:
  enabled: true
  irsa:
    accountId: "275662791714"
    roleName: "kanopy-staging-cicd-irsa"
